### ISSUE TITLE
How I can run my plugin test script?

### ISSUE THREAD

**Issue by WandyLau** [apache/cordova-plugin-test-framework#39]
I did not find how to run the test script anyway after read through the doc.

**Comment by WandyLau** [comment]
I implement the auto test, will this run automatically when to build the app?
How can I find the evidence of that?

**Comment by janpio** [comment]
See https://github.com/apache/cordova-plugin-test-framework#harness

**Comment by WandyLau** [comment]
@janpio Yes, I have read this. After I add the plugin as well as test to the project, the test case will be run when to run the APP?

**Comment by janpio** [comment]
If you also do what the documentation says (change the start page), yes - you can run the tests from there. The changed start page is a test runner.

**Comment by WandyLau** [comment]
So the auto test will be fired from here, right?  I asked this because I can not find any clue that the test has been executed. Or should I have to execute specifically?

**Comment by WandyLau** [comment]
I just did as the document stats. But I can not find any proof that the test has been executed. 
The simulator would always be on `device ready` state. Did I miss anything?
<img width="242" alt="Screen Shot 2019-03-19 at 14 35 17" src="https://user-images.githubusercontent.com/2303377/54585133-44978600-4a54-11e9-8cad-f1c440effdd4.png">

**Comment by WandyLau** [comment]
And another question: I will have to test one by one if I got multi plugins?

**Comment by janpio** [comment]
You have to do what the document says:

> Change the start page in config.xml with <content src="cdvtests/index.html" /> or add a link to cdvtests/index.html from within your app.

The screenshot you posted still shows the default `index.html`, not the test runner.

**Comment by janpio** [comment]
> And another question: I will have to test one by one if I got multi plugins?

Please open a new issue for this unrelated question.

**Comment by WandyLau** [comment]
FYI @janpio  #41 #40
