### ISSUE TITLE
Update Jasmine to more recent version

### ISSUE THREAD

**Issue by peitschie** [apache/cordova-plugin-test-framework#44]
# Feature Request
It would be great to have a more modern version of jasmine available in the test framework.

## Motivation Behind Feature
Newer versions of jasmine (even as old as 2.8) have better support for async tests via promise-based interfaces. Once promise interfaces are available, `async/await` can be used to write much easier to read and understand tests.

## Feature Description
If it is desirable to stick with the current jasmine interface, the above feature is available within the 2.X series: https://jasmine.github.io/2.8/introduction#section-Asynchronous_Support

If there is appetite for a bigger, potentially breaking change, jasmine is now up to v3.5

## Alternatives or Workarounds
There are some external libraries (e.g., jest-jasmine) that apply a similar transform to the jasmine interfaces. These are quite fiddly to get working in a pristine environment however.

If this feature might be desired, please let me know, as I'm happy to raise a pull request to implement this!

**Comment by timbru31** [comment]
PRs are more than welcome ;)
